In [8]:
import pandas as pd
import os

In [10]:
cwd = os.getcwd()
print(cwd)

/Users/bibashnepali/Desktop/AI_Data_Intelligence/ai_data_intelligence/notebooks

In [11]:
load_data = pd.read_csv("/Users/bibashnepali/Desktop/AI_Data_Intelligence/ai_data_intelligence/data/games.csv")

In [12]:
df = pd.DataFrame(load_data)

In [13]:
df.head(10)

,game_id,title,platform,platform_type,platform_maker,platform_generation,genre,year,publisher,developer,...,online_multiplayer,dlc_released,microtransactions,loot_boxes,game_pass_available,vr_support,goty_nominated,goty_won,how_long_to_beat_main_hrs,how_long_to_beat_completionist_hrs
0,G000001,eFootball 2023,Game Boy,Handheld,Nintendo,4,Sports,1990,CD Projekt,Deep Silver,...,1,1,0,0,0,0,0,0,31.8,86.1
1,G000002,Doom 3,Xbox,Console,Microsoft,6,Rhythm,2004,Ubisoft,Ubisoft,...,0,1,1,0,0,0,0,0,13.1,55.4
2,G000003,God of Fire,PC,PC,Various,0,Misc,1988,Microsoft Studios,Microsoft Studios,...,0,0,0,0,0,0,0,0,9.8,20.9
3,G000004,Call of Duty: Rising Sun,Mobile (Android),Mobile,Google,0,Shooter,2017,InXile Entertainment,InXile Entertainment,...,1,1,1,0,0,0,0,0,9.1,44.8
4,G000005,Fortnite 3,Nintendo 64,Console,Nintendo,5,Battle Royale,1999,Naughty Dog,id Software,...,1,0,1,0,0,0,0,0,150.8,322.3
5,G000006,Need for Speed: Shadow War,PC,PC,Various,0,Racing,2003,2K Games,id Software,...,0,1,0,0,0,0,0,0,14.1,37.7
6,G000007,Valorant 3,NES,Console,Nintendo,3,Shooter,1993,Activision Blizzard,Activision Blizzard,...,1,1,0,0,0,0,1,0,12.6,62.1
7,G000008,FIFA 2024,NES,Console,Nintendo,3,Sports,1990,Sega,Obsidian Entertainment,...,1,1,0,0,0,0,0,0,14.5,30.1
8,G000009,Battlefield Odyssey,Xbox 360,Console,Microsoft,7,Shooter,2005,Humble Games,Humble Games,...,1,0,1,0,0,0,0,0,4.2,17.6
9,G000010,Kirby's Knight,Atari 2600,Console,Atari,2,Platform,1990,2K Games,Epic Games,...,0,1,0,0,0,0,0,0,15.1,64.1

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 35 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   game_id                             50000 non-null  str
 1   title                               50000 non-null  str
 2   platform                            50000 non-null  str
 3   platform_type                       50000 non-null  str
 4   platform_maker                      50000 non-null  str
 5   platform_generation                 50000 non-null  int64
 6   genre                               50000 non-null  str
 7   year                                50000 non-null  int64
 8   publisher                           50000 non-null  str
 9   developer                           50000 non-null  str
 10  publisher_region                    50000 non-null  str
 11  publisher_tier                      50000 non-null  str
 12  esrb_rating                         50000 non-null  str
 13  metacritic_score                    50000 non-null  int64
 14  user_score                          50000 non-null  float64
 15  critic_review_count                 50000 non-null  int64
 16  user_review_count                   50000 non-null  int64
 17  na_sales_million                    50000 non-null  float64
 18  eu_sales_million                    50000 non-null  float64
 19  jp_sales_million                    50000 non-null  float64
 20  other_sales_million                 50000 non-null  float64
 21  global_sales_million                50000 non-null  float64
 22  estimated_revenue_million_usd       50000 non-null  float64
 23  launch_price_usd                    50000 non-null  float64
 24  is_sequel                           50000 non-null  int64
 25  online_multiplayer                  50000 non-null  int64
 26  dlc_released                        50000 non-null  int64
 27  microtransactions                   50000 non-null  int64
 28  loot_boxes                          50000 non-null  int64
 29  game_pass_available                 50000 non-null  int64
 30  vr_support                          50000 non-null  int64
 31  goty_nominated                      50000 non-null  int64
 32  goty_won                            50000 non-null  int64
 33  how_long_to_beat_main_hrs           50000 non-null  float64
 34  how_long_to_beat_completionist_hrs  50000 non-null  float64
dtypes: float64(10), int64(14), str(11)
memory usage: 13.4 MB

In [ ]:
df.describe()

,game_id,title,platform,platform_type,platform_maker,platform_generation,genre,year,publisher,developer,...,online_multiplayer,dlc_released,microtransactions,loot_boxes,game_pass_available,vr_support,goty_nominated,goty_won,how_long_to_beat_main_hrs,how_long_to_beat_completionist_hrs
count,50000,50000,50000,50000,50000,50000.000000,50000,50000.000000,50000,50000,...,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.00000,50000.000000
unique,50000,1391,33,7,8,NaN,20,NaN,51,51,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,G000001,Devil May Ascend,PC,Console,Nintendo,NaN,Action,NaN,Sega,Sega,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,1,195,6305,24495,16815,NaN,7496,NaN,1560,1355,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,4.397120,NaN,2007.479640,NaN,NaN,...,0.506960,0.623140,0.310980,0.065020,0.036520,0.024420,0.044640,0.006760,24.84839,87.036108
std,NaN,NaN,NaN,NaN,NaN,3.256757,NaN,11.673832,NaN,NaN,...,0.499957,0.484604,0.462899,0.246564,0.187582,0.154351,0.206514,0.081942,34.73811,126.802256
min,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,1985.000000,NaN,NaN,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.00000,2.000000
25%,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,1998.000000,NaN,NaN,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,9.00000,29.400000
50%,NaN,NaN,NaN,NaN,NaN,5.000000,NaN,2008.000000,NaN,NaN,...,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,13.20000,46.100000
75%,NaN,NaN,NaN,NaN,NaN,7.000000,NaN,2017.000000,NaN,NaN,...,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,24.10000,85.200000
max,NaN,NaN,NaN,NaN,NaN,10.000000,NaN,2026.000000,NaN,NaN,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,377.50000,1685.000000

In [22]:
if (df.isnull().sum().sum() == 0):
    print("No missing values in the dataset.")

No missing values in the dataset.